In [6]:
import pandas as pd
print("successfully imported library")
df=pd.read_csv("student_performance.csv")
df.head()

successfully imported library

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [8]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

In [11]:
#shape:(tuple of number_of rows and numberof_columns)(rows,col)
print(df.shape)
print(df.shape[0])
print(df.shape[1])

(30, 13)
30
13

In [12]:
#view all column name
print("columns in the datasets")
print(df.columns.tolist())

columns in the datasets
['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [15]:
# check datatype of each column
print(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [16]:
# statistical summary
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [27]:
import numpy as np
df.loc[:4, 'math_score'] = np.nan
print(df.isnull().sum())

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               5
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

In [32]:
print(df['department'].unique())

['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [33]:
print(df['department'].value_counts())

department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [34]:
print(df['city'].value_counts())

city
Kochi                 2
Lucknow               2
Thiruvananthapuram    2
Agra                  2
Kolkata               2
Hyderabad             1
Mumbai                1
Delhi                 1
Ahmedabad             1
Varanasi              1
Bangalore             1
Pune                  1
Jaipur                1
Mysore                1
Thrissur              1
Bhopal                1
Chennai               1
Patna                 1
Nagpur                1
Dehradun              1
Chandigarh            1
Surat                 1
Allahabad             1
Kanpur                1
Indore                1
Name: count, dtype: int64

In [35]:
print(df['gender'].value_counts())

gender
Male      15
Female    15
Name: count, dtype: int64

In [41]:
city_f = df[ (df['city'] == 'Chennai') | (df['city'] == 'Mumbai') ]
display(city_f[['city','programming_score']])

       city  programming_score
0    Mumbai                 91
10  Chennai                 72

In [40]:
cs = df[ (df['department'] == 'Computer Science') ]
print(len(cs))
print(cs[['name','math_score','department']])

13
              name  math_score        department
0     Aarav Sharma         NaN  Computer Science
1      Priya Patel         NaN  Computer Science
4       Arjun Nair         NaN  Computer Science
7      Divya Singh        88.0  Computer Science
9       Ananya Das        95.0  Computer Science
12      Suresh Rao        83.0  Computer Science
14     Ajay Tiwari        71.0  Computer Science
17  Swati Kulkarni        90.0  Computer Science
19    Nisha Kapoor        79.0  Computer Science
21     Tanvi Mehta        93.0  Computer Science
24       Amit Bose        86.0  Computer Science
26   Gaurav Shukla        84.0  Computer Science
29  Akanksha Yadav        91.0  Computer Science

In [48]:
attendence=df[df['attendance_percentage']<=75]
print(len(attendence))

7

In [56]:
df['total_score']=df['math_score']+df['programming_score']+df['science_score']+df['english_score']
top=df.loc[df['total_score'].idxmax()]
print(top)

student_id                           1010
name                           Ananya Das
age                                    19
gender                             Female
department               Computer Science
semester                                2
math_score                           95.0
science_score                          89
english_score                          90
programming_score                      97
attendance_percentage                  98
city                              Kolkata
admission_year                       2023
total_score                         371.0
Name: 9, dtype: object

In [57]:
top=df.loc[df['total_score'].idxmin()]
print(top)

student_id                       1017
name                     Manoj Pandey
age                                21
gender                           Male
department                      Civil
semester                            2
math_score                       56.0
science_score                      61
english_score                      55
programming_score                  38
attendance_percentage              65
city                            Patna
admission_year                   2023
total_score                     210.0
Name: 16, dtype: object